apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  creationTimestamp: "2024-07-04T01:10:40Z"
  name: ktop
spec:
  caveats: |
    * By default, ktop displays metrics for resources in the default namespace. You can override this behavior
    by providing a --namespace or use -A for all namespaces.
  description: |-
    This is a kubectl plugin for ktop, a top-like tool for displaying workload
    metrics for a running Kubernetes cluster.
  homepage: https://github.com/vladimirvivien/ktop
  platforms:
  - bin: kubectl-ktop
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: linux
    sha256: eb2e73eccb65693bbe882d2543acdffa96411b57b52f5ddb827b09b73c08468d
    uri: https://github.com/vladimirvivien/ktop/releases/download/v0.4.1/kubectl-ktop_v0.4.1_linux_arm64.tar.gz
  - bin: kubectl-ktop
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: linux
    sha256: 17a1e0d33c2f547e0514143e0a64ac72bdeb7cd7f13b4fbb12bf40c5ec6f70a6
    uri: https://github.com/vladimirvivien/ktop/releases/download/v0.4.1/kubectl-ktop_v0.4.1_linux_amd64.tar.gz
  - bin: kubectl-ktop
    files: null
    selector:
      matchLabels:
        arch: arm64
        os: darwin
    sha256: d6fcdc95e3d04c2db08962ea2e9bbb977ffc25dc2a09a6ac7d0a714897f12866
    uri: https://github.com/vladimirvivien/ktop/releases/download/v0.4.1/kubectl-ktop_v0.4.1_darwin_arm64.tar.gz
  - bin: kubectl-ktop
    files: null
    selector:
      matchLabels:
        arch: amd64
        os: darwin
    sha256: 60adecbcd796bc312aa0a5ee34790fddcf66baa16cefec41084be1e063cdbd83
    uri: https://github.com/vladimirvivien/ktop/releases/download/v0.4.1/kubectl-ktop_v0.4.1_darwin_amd64.tar.gz
  shortDescription: A top tool to display workload metrics
  version: v0.4.1
status:
  source:
    name: default
