#!/usr/bin/env bash
#
# custom $LESSOPEN filter that colorizes
# file/stdin using pygmentize/code2color
#
# see ~/.bash_profile for relevant LESS* variables
# as well as l() function that provides $LESSLEXER
#
# author: Erhhung Yuan (erhhung@alum.mit.edu)

file=$(basename "$1")
# use file extension if lexer
# is not explicitly specified
lexer="${LESSLEXER:-${file##*.}}"
style="${PYGMENTSTYLE:-stata-dark}"

case "$lexer" in
  yaml|yml)
    style='native'
    ;;
esac

_pygmentize() {
  pygmentize -f 256 "$@" -O style="$style" 2> /dev/null
}
bash_shebang() {
  head -1 "$1" | grep -Eq '^#!.*\b(ba)?sh' 2> /dev/null
}

if [ "$1" == '-' ]; then
  # stdin: guess the lexer ("-g") unless explicitly specified
  [ -z "$lexer" ] && _pygmentize -g || _pygmentize -l $lexer

elif [ -r "$1" ]; then
  # file is readable
  case "$lexer" in
    *json)
      jq -C . "$1"
      ;;
    *sh|bash*)
      _pygmentize -l sh "$1"
      ;;
    *)
      bash_shebang "$1" && _pygmentize -l sh "$1" \
         || PYGMENTSTYLE="$style" code2color "$1"
  esac
else
  exit 1
fi
